"""
train.py
========
Trains the Tamsui crowd-prediction model on the simulated dataset from
make_dataset.py and exports it to ../data/crowd_model.js so the website can run
it in the browser with no backend and no Python.

Run:   python3 ml/train.py
Output: data/crowd_model.js  (window.CROWD_MODEL = {...})

Model choice: a single, right-sized DecisionTreeRegressor. The simulator is
low-noise and we only ever predict for 16 known spots, so one interpretable tree
fits it tightly AND serialises to a small file (a deep Random Forest hit the same
accuracy but exported to ~5 MB — far too heavy for a web page). The export keeps
a generic `trees: [...]` shape (a list of one), so js/predict.js can average over
one or many trees without caring which model produced it.
"""

import json
import os
import datetime as dt

import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score

from make_dataset import build_dataset, feature_row, PATTERNS

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_PATH = os.path.normpath(os.path.join(HERE, "..", "data", "crowd_model.js"))

# Tree size: enough leaves to capture each spot's hourly curve (and the lone
# temple's blossom spike), small enough to stay light once serialised.
MAX_LEAVES = 2600
MIN_LEAF = 2


def make_model():
    return DecisionTreeRegressor(
        max_leaf_nodes=MAX_LEAVES, min_samples_leaf=MIN_LEAF, random_state=0,
    )


def export_trees(models, feature_names, metrics):
    """Serialise one-or-more sklearn trees to compact per-node arrays."""
    trees = []
    for est in models:
        t = est.tree_
        trees.append({
            "f": [int(x) for x in t.feature],                    # -2 at leaves
            "t": [round(float(x), 2) for x in t.threshold],
            "l": [int(x) for x in t.children_left],              # -1 at leaves
            "r": [int(x) for x in t.children_right],
            "v": [round(float(v.ravel()[0]), 1) for v in t.value],
        })
    return {
        "type": "decision_tree",
        "generated": dt.date.today().isoformat(),
        "n_features": len(feature_names),
        "feature_names": feature_names,
        "patterns": PATTERNS,
        "metrics": metrics,
        "trees": trees,
    }


def sanity_checks(model):
    """Print a few human-readable predictions to confirm the model is sane."""
    def pred(label, pop, pattern, weather, season, dow, hour, month, rain):
        x = np.array([feature_row(pop, pattern, weather, season, dow, hour, month, rain)])
        print(f"   {label:<46} -> {model.predict(x)[0]:5.1f}/100")

    print("\nSanity checks (0 = empty, 100 = packed):")
    pred("Old Street · Saturday 17:00",        96, "street", 0.5, None,       5, 17, 6, 0)
    pred("Old Street · Tuesday 10:00",         96, "street", 0.5, None,       1, 10, 6, 0)
    pred("Mangrove · Tuesday 10:00",           30, "nature", 0.6, None,       1, 10, 6, 0)
    pred("Hobe Fort · Saturday 17:00",         28, "indoor", 0.4, None,       5, 17, 6, 0)
    pred("Tianyuan · Sunday 10:00 (Mar)",      40, "temple", 0.5, (2, 3),     6, 10, 3, 0)
    pred("Tianyuan · Sunday 10:00 (Jun)",      40, "temple", 0.5, (2, 3),     6, 10, 6, 0)
    pred("Riverside · Saturday 17:00 (rain)",  92, "sunset", 0.7, None,       5, 17, 6, 1)


def main():
    print("Building dataset...")
    X, y, names = build_dataset()
    print(f"  {X.shape[0]:,} rows × {X.shape[1]} features")

    # Honest held-out metrics on a train/test split...
    X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=0)
    print(f"Training DecisionTree (≤{MAX_LEAVES} leaves)...")
    model = make_model().fit(X_tr, y_tr)
    pred_te = model.predict(X_te)
    mae = float(mean_absolute_error(y_te, pred_te))
    r2 = float(r2_score(y_te, pred_te))
    print(f"  Held-out MAE: {mae:.2f} crowd-points   |   Held-out R²: {r2:.3f}")

    # ...then refit on the FULL grid for the exported model (we only ever predict
    # for these exact spots, so we want the tightest fit to the simulator).
    model = make_model().fit(X, y)
    print(f"  Final tree: {model.get_n_leaves()} leaves, depth {model.get_depth()}")
    sanity_checks(model)

    payload = export_trees([model], names, {"mae": round(mae, 2), "r2": round(r2, 3)})
    js = "/* Auto-generated by ml/train.py — do not edit by hand. */\n"
    js += "window.CROWD_MODEL = " + json.dumps(payload, separators=(",", ":")) + ";\n"
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(js)
    size_kb = os.path.getsize(OUT_PATH) / 1024
    print(f"\nExported -> {OUT_PATH}  ({size_kb:.0f} KB)")


if __name__ == "__main__":
    main()
